#!/usr/bin/expect

if {$argc  < 4} {
    puts "Usage:"
    puts "$argv0 cmd host user port [passwd]"
    exit 1
}

set cmd [lindex $argv 0]
set host [lindex $argv 1]
set acc [lindex $argv 2]
set port [lindex $argv 3]
set passwd [lindex $argv 4]

set passwderror 0
set timeout 30
spawn $cmd $acc@$host -p $port
expect {
    "*assword:*" {
        if { $passwderror -ne 1 } {
            puts "passwd is error"
            exit 2
        }
        if { "$passwd" != ""} {
            set timeout 1000
            set passwderror 1
            send "$passwd\r"
        }
        interact
        exp_continue
    }
    "*es/no)?*" {
        send "yes\r"
        exp_continue
    }
    timeout {
        puts "connect is timeout"
        exit 3
    }
    "* " {
        interact
    }
}

interact

